Get rid of scripts

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,10 +65,6 @@ orbs:
                         type: string
                         default: master
                 steps:
-                    - checkout
-                    - run: 
-                        name: Make scripts executable
-                        command: chmod +x .circleci/*.sh
                     - run:
                         name: Call remote smoke tests job
                         command: |
@@ -80,7 +76,52 @@ orbs:
                                 --request POST "https://circleci.com/api/v1.1/project/github/<< parameters.remote_repo >>/tree/<< parameters.remote_branch >>" > run_tests_cmd_job.json
                     - run:
                         name: Wait for smoke tests job to complete and report status
-                        command: .circleci/wait_for_remote_job.sh ${SMOKE_TEST_TOKEN} run_tests_cmd_job.json << parameters.remote_repo >> "Running Smoke Tests"
+                        command: |
+                            smoke_job_build_num=$(jq '.build_num' < run_tests_cmd_job.json)
+
+                            build_url="https://circleci.com/api/v1.1/project/github/<< parameters.remote_repo >>/${smoke_job_build_num}"
+
+                            smoke_result_file="smoke_result.json"
+                            smoke_step_name="Running Smoke Tests"
+
+                            echo "Waiting now for smoke tests job execution. See build ${build_url}."
+
+                            RUNNING=true
+                                while [ $RUNNING == true ]; do
+                                sleep 10;
+                                status=$(curl --silent --header "Accept: application/json" "${build_url}?circle-token=$1" | tee ${smoke_result_file} | jq -r '.status');
+                                echo 'running queued scheduled not_running' | grep --silent "$status" || RUNNING=false;
+                                echo -n "."
+                            done
+
+                            echo ""
+                            echo "Smoke tests ${build_url} finished with status ${status}"
+
+                            if [[ $status == 'fixed success' ]]
+                            then
+                                exit_code=0
+                            else
+                                exit_code=1
+
+                                # get the output_url property from the "Running Smoke Tests" job in the json response
+                                output_url=$(jq -r ".steps[] | select(.name == \"${smoke_step_name}\") | .actions[0].output_url" ${smoke_result_file});
+
+                                echo ""
+                                echo "Smoke tests error message:"
+                                echo ""
+
+                                if [ ! -z "${output_url}" ]
+                                then
+                                    # call the output url to fetch the error message and display it
+                                    error_message=$(curl --silent --compressed --header "Accept: application/json" "${output_url}" | jq -r '.[0].message');
+                                    echo -n "${error_message}" | tr -d '\r'
+                                else
+                                    # no output_url, unknown error
+                                    echo "Unknown error. Check the smoke test job execution logs for more details."
+                                fi
+                                echo ""
+                            fi
+                            exit $exit_code
             
 
 jobs:
